version: '2.1'
services:
  logger:
    build: ./logger
    ports:
      - "8080:8080"
    environment:
      EMBEDDED_MONGO_ARTIFACTS: /opt/lunarlogger/.embedmongo
    volumes:
      - .embedmongo:/opt/lunarlogger/.embedmongo
